# NLP Basics: What is Natural Language Processing & the Natural Language Toolkit?

### How to install NLTK (Natural Language Toolkit) on your local machine

Both sets of instructions below assume you already have Python installed. These instructions are taken directly from [http://www.nltk.org/install.html](http://www.nltk.org/install.html).

**Mac/Unix**

From the terminal:
Install NLTK: run `pip install -U nltk`


**Windows**

Install NLTK: [http://pypi.python.org/pypi/nltk](http://pypi.python.org/pypi/nltk)

## Download NLTK data

In [3]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [4]:
dir(nltk) #to show all the functions, attributes and methods available in nltk

['ARLSTem',
 'ARLSTem2',
 'AbstractLazySequence',
 'AffixTagger',
 'AlignedSent',
 'Alignment',
 'AnnotationTask',
 'ApplicationExpression',
 'Assignment',
 'BigramAssocMeasures',
 'BigramCollocationFinder',
 'BigramTagger',
 'BinaryMaxentFeatureEncoding',
 'BlanklineTokenizer',
 'BllipParser',
 'BottomUpChartParser',
 'BottomUpLeftCornerChartParser',
 'BottomUpProbabilisticChartParser',
 'Boxer',
 'BrillTagger',
 'BrillTaggerTrainer',
 'CFG',
 'CRFTagger',
 'CfgReadingCommand',
 'ChartParser',
 'ChunkParserI',
 'ChunkScore',
 'Cistem',
 'ClassifierBasedPOSTagger',
 'ClassifierBasedTagger',
 'ClassifierI',
 'ConcordanceIndex',
 'ConditionalExponentialClassifier',
 'ConditionalFreqDist',
 'ConditionalProbDist',
 'ConditionalProbDistI',
 'ConfusionMatrix',
 'ContextIndex',
 'ContextTagger',
 'ContingencyMeasures',
 'CoreNLPDependencyParser',
 'CoreNLPParser',
 'Counter',
 'CrossValidationProbDist',
 'DRS',
 'DecisionTreeClassifier',
 'DefaultTagger',
 'DependencyEvaluator',
 'DependencyGrammar',
 'DependencyGraph',
 'DependencyProduction',
 'DictionaryConditionalProbDist',
 'DictionaryProbDist',
 'DiscourseTester',
 'DrtExpression',
 'DrtGlueReadingCommand',
 'ELEProbDist',
 'EarleyChartParser',
 'Expression',
 'FStructure',
 'FeatDict',
 'FeatList',
 'FeatStruct',
 'FeatStructReader',
 'Feature',
 'FeatureBottomUpChartParser',
 'FeatureBottomUpLeftCornerChartParser',
 'FeatureChartParser',
 'FeatureEarleyChartParser',
 'FeatureIncrementalBottomUpChartParser',
 'FeatureIncrementalBottomUpLeftCornerChartParser',
 'FeatureIncrementalChartParser',
 'FeatureIncrementalTopDownChartParser',
 'FeatureTopDownChartParser',
 'FreqDist',
 'HTTPPasswordMgrWithDefaultRealm',
 'HeldoutProbDist',
 'HiddenMarkovModelTagger',
 'HiddenMarkovModelTrainer',
 'HunposTagger',
 'IBMModel',
 'IBMModel1',
 'IBMModel2',
 'IBMModel3',
 'IBMModel4',
 'IBMModel5',
 'ISRIStemmer',
 'ImmutableMultiParentedTree',
 'ImmutableParentedTree',
 'ImmutableProbabilisticMixIn',
 'ImmutableProbabilisticTree',
 'ImmutableTree',
 'IncrementalBottomUpChartParser',
 'IncrementalBottomUpLeftCornerChartParser',
 'IncrementalChartParser',
 'IncrementalLeftCornerChartParser',
 'IncrementalTopDownChartParser',
 'Index',
 'InsideChartParser',
 'JSONTaggedDecoder',
 'JSONTaggedEncoder',
 'KneserNeyProbDist',
 'LancasterStemmer',
 'LaplaceProbDist',
 'LazyConcatenation',
 'LazyEnumerate',
 'LazyIteratorList',
 'LazyMap',
 'LazySubsequence',
 'LazyZip',
 'LeftCornerChartParser',
 'LegalitySyllableTokenizer',
 'LidstoneProbDist',
 'LineTokenizer',
 'LogicalExpressionException',
 'LongestChartParser',
 'MLEProbDist',
 'MWETokenizer',
 'Mace',
 'MaceCommand',
 'MaltParser',
 'MaxentClassifier',
 'Model',
 'MultiClassifierI',
 'MultiParentedTree',
 'MutableProbDist',
 'NLTKWordTokenizer',
 'NaiveBayesClassifier',
 'NaiveBayesDependencyScorer',
 'NgramAssocMeasures',
 'NgramTagger',
 'NonprojectiveDependencyParser',
 'Nonterminal',
 'OrderedDict',
 'PCFG',
 'Paice',
 'ParallelProverBuilder',
 'ParallelProverBuilderCommand',
 'ParentedTree',
 'ParserI',
 'PerceptronTagger',
 'PhraseTable',
 'PorterStemmer',
 'PositiveNaiveBayesClassifier',
 'ProbDistI',
 'ProbabilisticDependencyGrammar',
 'ProbabilisticMixIn',
 'ProbabilisticNonprojectiveParser',
 'ProbabilisticProduction',
 'ProbabilisticProjectiveDependencyParser',
 'ProbabilisticTree',
 'Production',
 'ProjectiveDependencyParser',
 'Prover9',
 'Prover9Command',
 'ProxyBasicAuthHandler',
 'ProxyDigestAuthHandler',
 'ProxyHandler',
 'PunktSentenceTokenizer',
 'QuadgramAssocMeasures',
 'QuadgramCollocationFinder',
 'RSLPStemmer',
 'RTEFeatureExtractor',
 'RUS_PICKLE',
 'RandomChartParser',
 'RangeFeature',
 'ReadingCommand',
 'RecursiveDescentParser',
 'RegexpChunkParser',
 'RegexpParser',
 'RegexpStemmer',
 'RegexpTagger',
 'RegexpTokenizer',
 'ReppTokenizer',
 'ResolutionProver',
 'ResolutionProverCommand',
 'SExprTokenizer',
 'SLASH',
 'Senna',
 'SennaChunkTagger',
 'SennaNERTagger',
 'SennaTagger',
 'SequentialBackoffTagger',
 'ShiftReduceParser',
 'SimpleGoodTuringProbDist',
 'SklearnClassifier',
 'SlashFeature',
 'SnowballStemmer',
 'SpaceTokenizer',
 'StackDecoder',
 'StanfordNERTagger',
 'StanfordPOSTagger',
 'StanfordSegmenter',
 'StanfordTagger',
 'StemmerI',
 'SteppingChartParser',
 'SteppingRecursiveDescentParser',
 'SteppingShiftReduceParser',
 'SyllableTokenizer',
 'TYPE',
 'TabTokenizer',
 'TableauProver',
 'TableauProverCommand',
 'TaggerI',
 'TestGrammar',
 'Text',
 'TextCat',
 'TextCollection',
 'TextTilingTokenizer',
 'TnT',
 'TokenSearcher',
 'ToktokTokenizer',
 'TopDownChartParser',
 'TransitionParser',
 'Tree',
 'TreePrettyPrinter',
 'TreebankWordDetokenizer',
 'TreebankWordTokenizer',
 'Trie',
 'TrigramAssocMeasures',
 'TrigramCollocationFinder',
 'TrigramTagger',
 'TweetTokenizer',
 'TypedMaxentFeatureEncoding',
 'Undefined',
 'UniformProbDist',
 'UnigramTagger',
 'UnsortedChartParser',
 'Valuation',
 'Variable',
 'ViterbiParser',
 'WekaClassifier',
 'WhitespaceTokenizer',
 'WittenBellProbDist',
 'WordNetLemmatizer',
 'WordPunctTokenizer',
 '__author__',
 '__author_email__',
 '__builtins__',
 '__cached__',
 '__classifiers__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__keywords__',
 '__license__',
 '__loader__',
 '__longdescr__',
 '__maintainer__',
 '__maintainer_email__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__url__',
 '__version__',
 'accuracy',
 'acyclic_branches_depth_first',
 'acyclic_breadth_first',
 'acyclic_depth_first',
 'acyclic_dic2tree',
 'add_logs',
 'agreement',
 'align',
 'alignment_error_rate',
 'aline',
 'api',
 'app',
 'apply_features',
 'approxrand',
 'arity',
 'arlstem',
 'arlstem2',
 'association',
 'bigrams',
 'binary_distance',
 'binary_search_file',
 'binding_ops',
 'bisect',
 'blankline_tokenize',
 'bleu',
 'bleu_score',
 'bllip',
 'boolean_ops',
 'boxer',
 'bracket_parse',
 'breadth_first',
 'brill',
 'brill_trainer',
 'build_opener',
 'call_megam',
 'casual',
 'casual_tokenize',
 'ccg',
 'chain',
 'chart',
 'chat',
 'chomsky_normal_form',
 'choose',
 'chrf',
 'chrf_score',
 'chunk',
 'cistem',
 'classify',
 'clause',
 'clean_html',
 'clean_url',
 'cluster',
 'collapse_unary',
 'collections',
 'collocations',
 'combinations',
 'compat',
 'config_java',
 'config_megam',
 'config_weka',
 'conflicts',
 'confusionmatrix',
 'conllstr2tree',
 'conlltags2tree',
 'corenlp',
 'corpus',
 'crf',
 'custom_distance',
 'data',
 'decisiontree',
 'decorator',
 'decorators',
 'defaultdict',
 'demo',
 'dependencygraph',
 'deprecated',
 'deque',
 'destructive',
 'discourse',
 'distance',
 'download',
 'download_gui',
 'download_shell',
 'downloader',
 'draw',
 'drt',
 'earleychart',
 'edge_closure',
 'edges2dot',
 'edit_distance',
 'edit_distance_align',
 'elementtree_indent',
 'entropy',
 'equality_preds',
 'evaluate',
 'evaluate_sents',
 'everygrams',
 'extract',
 'extract_rels',
 'extract_test_sentences',
 'f_measure',
 'featstruct',
 'featurechart',
 'filestring',
 'find',
 'flatten',
 'fractional_presence',
 'gale_church',
 'gdfa',
 'getproxies',
 'ghd',
 'gleu',
 'gleu_score',
 'glue',
 'grammar',
 'grow_diag_final_and',
 'guess_encoding',
 'help',
 'hmm',
 'hunpos',
 'ibm1',
 'ibm2',
 'ibm3',
 'ibm4',
 'ibm5',
 'ibm_model',
 'ieerstr2tree',
 'in_idle',
 'induce_pcfg',
 'inference',
 'infile',
 'inspect',
 'install_opener',
 'internals',
 'interpret_sents',
 'interval_distance',
 'invert_dict',
 'invert_graph',
 'is_rel',
 'islice',
 'isri',
 'jaccard_distance',
 'json_tags',
 'jsontags',
 'lancaster',
 'lazyimport',
 'legality_principle',
 'lfg',
 'line_tokenize',
 'linearlogic',
 'lm',
 'load',
 'load_parser',
 'locale',
 'log_likelihood',
 'logic',
 'mace',
 'malt',
 'map_tag',
 'mapping',
 'masi_distance',
 'maxent',
 'megam',
 'memoize',
 'meteor',
 'meteor_score',
 'metrics',
 'misc',
 'mwe',
 'naivebayes',
 'ne_chunk',
 'ne_chunk_sents',
 'ngrams',
 'nist',
 'nist_score',
 'nonprojectivedependencyparser',
 'nonterminals',
 'numpy',
 'os',
 'pad_sequence',
 'paice',
 'pairwise',
 'parallelize_preprocess',
 'parse',
 'parse_sents',
 'pchart',
 'perceptron',
 'phrase_based',
 'pk',
 'porter',
 'pos_tag',
 'pos_tag_sents',
 'positivenaivebayes',
 'pprint',
 'pr',
 'precision',
 'presence',
 'print_string',
 'probability',
 'projectivedependencyparser',
 'prover9',
 'punkt',
 'pydoc',
 'raise_unorderable_types',
 'ranks_from_scores',
 'ranks_from_sequence',
 're',
 're_show',
 'read_grammar',
 'read_logic',
 'read_valuation',
 'recall',
 'recursivedescent',
 'regexp',
 'regexp_span_tokenize',
 'regexp_tokenize',
 'register_tag',
 'relextract',
 'repp',
 'resolution',
 'ribes',
 'ribes_score',
 'root_semrep',
 'rslp',
 'rte_classifier',
 'rte_classify',
 'rte_features',
 'rtuple',
 'scikitlearn',
 'scores',
 'segmentation',
 'sem',
 'senna',
 'sent_tokenize',
 'sequential',
 'set2rel',
 'set_proxy',
 'sexpr',
 'sexpr_tokenize',
 'shiftreduce',
 'simple',
 'sinica_parse',
 'skipgrams',
 'skolemize',
 'slice_bounds',
 'snowball',
 'sonority_sequencing',
 'spearman',
 'spearman_correlation',
 'stack_decoder',
 'stanford',
 'stanford_segmenter',
 'stem',
 'str2tuple',
 'string_span_tokenize',
 'subprocess',
 'subsumes',
 'sum_logs',
 'tableau',
 'tadm',
 'tag',
 'tagset_mapping',
 'tagstr2tree',
 'tbl',
 'tee',
 'text',
 'textcat',
 'texttiling',
 'textwrap',
 'tkinter',
 'tnt',
 'tokenize',
 'tokenwrap',
 'toktok',
 'toolbox',
 'total_ordering',
 'trace',
 'transitionparser',
 'transitive_closure',
 'translate',
 'tree',
 'tree2conllstr',
 'tree2conlltags',
 'treebank',
 'trigrams',
 'tuple2str',
 'un_chomsky_normal_form',
 'unify',
 'unique_list',
 'untag',
 'unweighted_minimum_spanning_dict',
 'unweighted_minimum_spanning_digraph',
 'unweighted_minimum_spanning_tree',
 'usage',
 'util',
 'version_file',
 'viterbi',
 'warnings',
 'weka',
 'windowdiff',
 'word_tokenize',
 'wordnet',
 'wordpunct_tokenize',
 'wsd']

### We will be working with SPAM/HAM SMS data

In [5]:
import pandas as pd
data = pd.read_csv("SMSSpamCollection.tsv",sep='\t',header=None)
data.head()

      0                                                  1
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham                I HAVE A DATE ON SUNDAY WITH WILL!!

In [6]:
data.columns = ['label','body_text']

### Explore the dataset

In [9]:
# what is the dimension of the data
data.shape

(5568, 2)

In [13]:
# what is the distribution of labels
data.label.value_counts(normalize=True)*100

label
ham     86.602011
spam    13.397989
Name: proportion, dtype: float64

In [23]:
data['body_text'][19]

'Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?'

# NLP Basics

### Pre-processing text data

Cleaning up the text data is necessary to highlight attributes that you're going to want your machine learning system to pick up on. Cleaning (or pre-processing) the data typically consists of a number of steps:
1. **Remove punctuation**
2. **Tokenization**
3. **Remove stopwords**
4. Lemmatize/Stem

The first three steps are covered in this chapter as they're implemented in pretty much any text cleaning pipeline. Lemmatizing and stemming are covered in the next chapter as they're helpful but not critical.

## Remove Punctuation

In [26]:
from string import punctuation as punct
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
". Ard 3 smth lor. " == " Ard 3 smth lor "

False

In [28]:
def remove_punctuation(text):
    text_noPunct = "".join([char for char in text if char not in punct])
    return text_noPunct

data['body_text_clean'] = data['body_text'].apply(lambda x: remove_punctuation(x))
data.head()

,label,body_text,body_text_clean
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL

## Tokenization

 Tokenizing is splitting some string or sentence into a list of words.

In [30]:
import re # re -> regular expression

def tokenize(text):
    tokens = re.split('\W+', text) #\W+ -> splits text by non word characters
    return tokens

data['body_text_tokenized'] = data['body_text_clean'].apply(lambda x: tokenize(x))
data.head()

<>:4: SyntaxWarning: invalid escape sequence '\W'
<>:4: SyntaxWarning: invalid escape sequence '\W'
C:\Users\ayray\AppData\Local\Temp\ipykernel_22108\2021857233.py:4: SyntaxWarning: invalid escape sequence '\W'
  tokens = re.split('\W+', text) #\W+ -> splits text by non word characters

,label,body_text,body_text_clean,body_text_tokenized
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"

## Removing Stopwords

Stop words are a set of commonly used words in any language. For example, in English, “the”, “is” and “and”, would easily qualify as stop words.

They provide no meaningful information, especially if we are building a text classification model. Therefore, we have to remove stopwords from our dataset.

As the frequency of stop words are too high, removing them from the corpus results in much smaller data in terms of size. Reduced size results in faster computations on text data and the text classification model need to deal with a lesser number of features resulting in a robust model.

In [32]:

'I willing to take risk starting my profession from scratch.'

'willing take risk starting profession scratch.'

'willing take risk starting profession scratch.'

In [33]:
import nltk
# nltk.download('stopwords')
sw = nltk.corpus.stopwords.words('english')

In [34]:
sw

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [35]:
def rem_stopwords(tokenized_list):
    text_noStopWords = [i for i in tokenized_list if i not in sw]
    return text_noStopWords

data['body_text_NoStopWords'] = data['body_text_tokenized'].apply(lambda x: rem_stopwords(x))
data.head()

,label,body_text,body_text_clean,body_text_tokenized,body_text_NoStopWords
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"

## Stemming

Stemming is a text preprocessing technique used in natural language processing (NLP) to reduce words to their root or base form. The goal of stemming is to simplify and standardize words, which helps improve the performance of information retrieval, text classification, and other NLP tasks. By transforming words to their stems, NLP models can treat different forms of the same word as a single entity, reducing the complexity of the text data.

For example, stemming would reduce the words “running,” “runner,” and “runs” to their stem “run.” This allows the NLP model to recognize that these words share a common concept or meaning, even though their forms are different.

Stemming algorithms typically work by removing or replacing word suffixes or prefixes, based on a set of predefined rules or heuristics. Some common stemming algorithms include the Porter Stemmer, Lancaster Stemmer, and Snowball Stemmer.

There are multiple types of Stemmers:

1. Porter Stemmer
2. Snowball Stemmer
3. Lancaster Stemmer
4. Regex-based Stemmer

In [37]:
PS = nltk.PorterStemmer() ## calling PorterStemmer function from nltk

def stemming(text):
    text = [PS.stem(word) for word in text]
    return text

data['body_text_stemmed'] = data['body_text_NoStopWords'].apply(lambda x: rem_stopwords(x))
data.head(25)

,label,body_text,body_text_clean,body_text_tokenized,body_text_NoStopWords,body_text_stemmed
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather...","[Ive, searching, right, words, thank, breather..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around...","[Nah, I, dont, think, goes, usf, lives, around..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like...","[Even, brother, like, speak, They, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"
5,ham,As per your request 'Melle Melle (Oru Minnamin...,As per your request Melle Melle Oru Minnaminun...,"[As, per, your, request, Melle, Melle, Oru, Mi...","[As, per, request, Melle, Melle, Oru, Minnamin...","[As, per, request, Melle, Melle, Oru, Minnamin..."
6,spam,WINNER!! As a valued network customer you have...,WINNER As a valued network customer you have b...,"[WINNER, As, a, valued, network, customer, you...","[WINNER, As, valued, network, customer, select...","[WINNER, As, valued, network, customer, select..."
7,spam,Had your mobile 11 months or more? U R entitle...,Had your mobile 11 months or more U R entitled...,"[Had, your, mobile, 11, months, or, more, U, R...","[Had, mobile, 11, months, U, R, entitled, Upda...","[Had, mobile, 11, months, U, R, entitled, Upda..."
8,ham,I'm gonna be home soon and i don't want to tal...,Im gonna be home soon and i dont want to talk ...,"[Im, gonna, be, home, soon, and, i, dont, want...","[Im, gonna, home, soon, dont, want, talk, stuf...","[Im, gonna, home, soon, dont, want, talk, stuf..."
9,spam,"SIX chances to win CASH! From 100 to 20,000 po...",SIX chances to win CASH From 100 to 20000 poun...,"[SIX, chances, to, win, CASH, From, 100, to, 2...","[SIX, chances, win, CASH, From, 100, 20000, po...","[SIX, chances, win, CASH, From, 100, 20000, po..."
10,spam,URGENT! You have won a 1 week FREE membership ...,URGENT You have won a 1 week FREE membership i...,"[URGENT, You, have, won, a, 1, week, FREE, mem...","[URGENT, You, 1, week, FREE, membership, 10000...","[URGENT, You, 1, week, FREE, membership, 10000..."
11,spam,"XXXMobileMovieClub: To use your credit, click ...",XXXMobileMovieClub To use your credit click th...,"[XXXMobileMovieClub, To, use, your, credit, cl...","[XXXMobileMovieClub, To, use, credit, click, W...","[XXXMobileMovieClub, To, use, credit, click, W..."
12,ham,Oh k...i'm watching here:),Oh kim watching here,"[Oh, kim, watching, here]","[Oh, kim, watching]","[Oh, kim, watching]"
13,ham,Eh u remember how 2 spell his name... Yes i di...,Eh u remember how 2 spell his name Yes i did H...,"[Eh, u, remember, how, 2, spell, his, name, Ye...","[Eh, u, remember, 2, spell, name, Yes, He, v, ...","[Eh, u, remember, 2, spell, name, Yes, He, v, ..."
14,ham,Fine if thats the way u feel. Thats the way ...,Fine if thats the way u feel Thats the way i...,"[Fine, if, that, s, the, way, u, feel, That, s...","[Fine, way, u, feel, That, way, gota, b]","[Fine, way, u, feel, That, way, gota, b]"
15,spam,England v Macedonia - dont miss the goals/team...,England v Macedonia dont miss the goalsteam n...,"[England, v, Macedonia, dont, miss, the, goals...","[England, v, Macedonia, dont, miss, goalsteam,...","[England, v, Macedonia, dont, miss, goalsteam,..."
16,ham,Is that seriously how you spell his name?,Is that seriously how you spell his name,"[Is, that, seriously, how, you, spell, his, name]","[Is, seriously, spell, name]","[Is, seriously, spell, name]"
17,ham,I‘m going to try for 2 months ha ha only joking,I‘m going to try for 2 months ha ha only joking,"[I, m, going, to, try, for, 2, months, ha, ha,...","[I, going, try, 2, months, ha, ha, joking]","[I, going, try, 2, months, ha, ha, joking]"
18,ham,So ü pay first lar... Then when is da stock co...,So ü pay first lar Then when is da stock comin,"[So, ü, pay, first, lar, Then, when, is, da, s...","[So, ü, pay, first, lar, Then, da, stock, comin]","[So, ü, pay, first, lar, Then, da, stock, comin]"
19,ham,Aft i finish my lunch then i go str down lor. ...,Aft i finish my lunch then i go str down lor A...,"[Aft, i, finish, my, lunch, then, i, go, str, ...","[Aft, finish, lunch, go, str, lor, Ard, 3, smt...","[Aft, finish, lunch, go, str, lor, Ard, 3, smt..."
20,ham,Ffffffffff. Alright no way I can meet up with ...,Ffffffffff Alright no way I can meet up with y...,"[Ffffffffff, Alright, no, way, I, can, meet, u...","[Ffffffffff, Alright, way, I, meet, sooner]","[Ffffffffff, Alright, way, I, meet, sooner]"
21,ham,Just forced myself to eat a slice. I'm really ...,Just forced myself to eat a slice Im really no...,"[Just, forced, myself, to, eat, a, slice, Im, ...","[Just, forced, eat, slice, Im, really, hungry,...","[Just, forced, eat, slice, Im, really, hungry,..."
22,ham,Lol your always so convincing.,Lol your always so convincing,"[Lol, your, always, so, convincing]","[Lol, always, convincing]","[Lol, always, convincing]"
23,ham,Did you catch the bus ? Are you frying an egg ...,Did you catch the bus Are you frying an egg ...,"[Did, you, catch, the, bus, Are, you, frying, ...","[Did, catch, bus, Are, frying, egg, Did, make,...","[Did, catch, bus, Are, frying, egg, Did, make,..."
24,ham,"I'm back &amp; we're packing the car now, I'll...",Im back amp were packing the car now Ill let y...,"[Im, back, amp, were, packing, the, car, now, ...","[Im, back, amp, packing, car, Ill, let, know, ...","[Im, back, amp, packing, car, Ill, let, know, ..."

## Lemmatization

This is the process of grouping together the inflected forms of a word so they can be analyzed as a single term, identified by the word's lemme. Lemmatizing is using vocabulary analysis of words to remove inflectional endings and return to the dictionary form of a word.

Lemmatization is a text pre-processing technique used in natural language processing (NLP) models to break a word down to its root meaning to identify similarities. For example, a lemmatization algorithm would reduce the word 'better' to its root word, or lemme, 'good'. 

In stemming, a part of the word is just chopped off at the tail end to arrive at the stem of the word. There are different algorithms used to find out how many characters have to be chopped off, but the algorithms don’t actually know the meaning of the word in the language it belongs to. In lemmatization, the algorithms do have this knowledge. In fact, you can even say that these algorithms refer to a dictionary to understand the meaning of the word before reducing it to its root word.

The obvious advantage of lemmatization is that it is more accurate than stemming. So, if you’re dealing with an NLP application such as a chat bot or a virtual assistant, where understanding the meaning of the dialogue is crucial, lemmatization would be more useful. But this accuracy comes at a cost.

Because lemmatization involves deriving the meaning of a word from something like a dictionary, it’s very time consuming. So most lemmatization algorithms are slower compared to their stemming counterparts. There is also a computation overhead for lemmatization, however, in most machine learning problems, computational resources are rarely a cause of concern.

In [43]:
wn = nltk.WordNetLemmatizer()

def lemmatizing(tokenized_text):
    text = [wn.lemmatize(word) for word in tokenized_text]
    return text

data['body_text_lemmatized'] = data['body_text_NoStopWords'].apply(lambda x: lemmatizing(x))

data.head(10)

,label,body_text,body_text_clean,body_text_tokenized,body_text_NoStopWords,body_text_stemmed,body_text_lemmatized
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather...","[Ive, searching, right, words, thank, breather...","[Ive, searching, right, word, thank, breather,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around...","[Nah, I, dont, think, goes, usf, lives, around...","[Nah, I, dont, think, go, usf, life, around, t..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like...","[Even, brother, like, speak, They, treat, like...","[Even, brother, like, speak, They, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"
5,ham,As per your request 'Melle Melle (Oru Minnamin...,As per your request Melle Melle Oru Minnaminun...,"[As, per, your, request, Melle, Melle, Oru, Mi...","[As, per, request, Melle, Melle, Oru, Minnamin...","[As, per, request, Melle, Melle, Oru, Minnamin...","[As, per, request, Melle, Melle, Oru, Minnamin..."
6,spam,WINNER!! As a valued network customer you have...,WINNER As a valued network customer you have b...,"[WINNER, As, a, valued, network, customer, you...","[WINNER, As, valued, network, customer, select...","[WINNER, As, valued, network, customer, select...","[WINNER, As, valued, network, customer, select..."
7,spam,Had your mobile 11 months or more? U R entitle...,Had your mobile 11 months or more U R entitled...,"[Had, your, mobile, 11, months, or, more, U, R...","[Had, mobile, 11, months, U, R, entitled, Upda...","[Had, mobile, 11, months, U, R, entitled, Upda...","[Had, mobile, 11, month, U, R, entitled, Updat..."
8,ham,I'm gonna be home soon and i don't want to tal...,Im gonna be home soon and i dont want to talk ...,"[Im, gonna, be, home, soon, and, i, dont, want...","[Im, gonna, home, soon, dont, want, talk, stuf...","[Im, gonna, home, soon, dont, want, talk, stuf...","[Im, gonna, home, soon, dont, want, talk, stuf..."
9,spam,"SIX chances to win CASH! From 100 to 20,000 po...",SIX chances to win CASH From 100 to 20000 poun...,"[SIX, chances, to, win, CASH, From, 100, to, 2...","[SIX, chances, win, CASH, From, 100, 20000, po...","[SIX, chances, win, CASH, From, 100, 20000, po...","[SIX, chance, win, CASH, From, 100, 20000, pou..."

## Vectorization of Raw text data

converting text to vectors/numbers

In [67]:
import pandas as pd
import re
import string
import nltk

data = pd.read_csv("SMSSpamCollection.tsv",sep='\t',header=None)
data.columns = ['label','body_text']

stopwords = nltk.corpus.stopwords.words('english')
wn = nltk.WordNetLemmatizer()

def clean_text(text):
    text = "".join([char.lower() for char in text if char not in string.punctuation])
    tokens = re.split('\W+',text)
    text = [i for i in tokens if i not in stopwords]
    text = [wn.lemmatize(word) for word in text]
    return text

data['cleaned_text'] = data['body_text'].apply(lambda x: clean_text(x))
data.head()

<>:14: SyntaxWarning: invalid escape sequence '\W'
<>:14: SyntaxWarning: invalid escape sequence '\W'
C:\Users\ayray\AppData\Local\Temp\ipykernel_22108\1928793232.py:14: SyntaxWarning: invalid escape sequence '\W'
  tokens = re.split('\W+',text)

,label,body_text,cleaned_text
0,ham,I've been searching for the right words to tha...,"[ive, searching, right, word, thank, breather,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,"[free, entry, 2, wkly, comp, win, fa, cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...","[nah, dont, think, go, usf, life, around, though]"
3,ham,Even my brother is not like to speak with me. ...,"[even, brother, like, speak, treat, like, aid,..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,"[date, sunday]"

### Count vectorization 

Creates a document-term matrix where the entry of each cell will be a count of the number of times that word occurred in that document.

In [68]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(analyzer = clean_text)
X_counts = count_vect.fit_transform(data['body_text'])
print(X_counts.shape)

(5568, 8914)

In [58]:
display(pd.DataFrame(X_counts.toarray()))

,0,1,2,3,4,5,6,7,8,9,...,8904,8905,8906,8907,8908,8909,8910,8911,8912,8913
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5564,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5565,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5566,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### N-Grams Vectorization

Creates a document-term matrix where counts still occupy the cell but instead of the columns representing single terms, they represent all combinations of adjacent words of length n in your text.

"NLP is an interesting topic"

| n | Name      | Tokens                                                         |
|---|-----------|----------------------------------------------------------------|
| 2 | bigram    | ["nlp is", "is an", "an interesting", "interesting topic"]      |
| 3 | trigram   | ["nlp is an", "is an interesting", "an interesting topic"] |
| 4 | four-gram | ["nlp is an interesting", "is an interesting topic"]    |

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(analyzer = clean_text, ngram_range = (2,4))
X_counts_ngram = count_vect.fit_transform(data['body_text'])
print(X_counts_ngram.shape)

C:\Users\ayray\Python312\Lib\site-packages\sklearn\feature_extraction\text.py:541: UserWarning: The parameter 'ngram_range' will not be used since 'analyzer' is callable'
  warnings.warn(

(5568, 8914)

In [70]:
data_sample = data[0:20]

ngram_vect_sample = CountVectorizer(ngram_range=(2,4), analyzer = clean_text)
X_counts_sample = ngram_vect_sample.fit_transform(data_sample['cleaned_text'])
print(X_counts_sample.shape)
print(ngram_vect_sample.get_feature_names_out())

X_counts_df = pd.DataFrame(X_counts_sample.toarray())
X_counts_df.columns = ngram_vect_sample.get_feature_names_out()
X_counts_df

(20, 20)
['aftfinishlunchgostrlorard3smthlorufinishurlunchalready' 'datesunday'
 'ehuremember2spellnameyesvnaughtymakevwet'
 'englandvmacedoniadontmissgoalsteamnewstxturnationalteam87077egengland87077trywalesscotland4txtú120poboxox36504w45wq16'
 'evenbrotherlikespeaktreatlikeaidpatent' 'finewayufeelwaygotab'
 'freeentry2wklycompwinfacupfinaltkts21stmay2005textfa87121receiveentryquestionstdtxtratetcsapply08452810075over18s'
 'goingtry2monthhahajoking'
 'imgonnahomesoondontwanttalkstuffanymoretonightkivecriedenoughtoday'
 'ivesearchingrightwordthankbreatherpromisewonttakehelpgrantedfulfilpromisewonderfulblessingtime'
 'mobile11monthurentitledupdatelatestcolourmobilecamerafreecallmobileupdatecofree08002986030'
 'nahdontthinkgousflifearoundthough' 'ohkimwatching'
 'perrequestmellemelleoruminnaminungintenurunguvettamsetcallertunecallerpress9copyfriendcallertune'
 'seriouslyspellname'
 'sixchancewincash10020000poundtxtcsh11send87575cost150pday6days16tsandcsapplyreplyhl4info'
 'urgent1weekfreemembership100000prizejackpottxtwordclaim81010tcwwwdbuknetlccltdpobox4403ldnw1a7rw18'
 'winnervaluednetworkcustomerselectedreceivea900prizerewardclaimcall09061701461claimcodekl341valid12hour'
 'xxxmobilemovieclubusecreditclickwaplinknexttxtmessageclickhttpwapxxxmobilemovieclubcomnqjkgighjjgcbl'
 'üpayfirstlardastockcomin']

,aftfinishlunchgostrlorard3smthlorufinishurlunchalready,datesunday,ehuremember2spellnameyesvnaughtymakevwet,englandvmacedoniadontmissgoalsteamnewstxturnationalteam87077egengland87077trywalesscotland4txtú120poboxox36504w45wq16,evenbrotherlikespeaktreatlikeaidpatent,finewayufeelwaygotab,freeentry2wklycompwinfacupfinaltkts21stmay2005textfa87121receiveentryquestionstdtxtratetcsapply08452810075over18s,goingtry2monthhahajoking,imgonnahomesoondontwanttalkstuffanymoretonightkivecriedenoughtoday,ivesearchingrightwordthankbreatherpromisewonttakehelpgrantedfulfilpromisewonderfulblessingtime,mobile11monthurentitledupdatelatestcolourmobilecamerafreecallmobileupdatecofree08002986030,nahdontthinkgousflifearoundthough,ohkimwatching,perrequestmellemelleoruminnaminungintenurunguvettamsetcallertunecallerpress9copyfriendcallertune,seriouslyspellname,sixchancewincash10020000poundtxtcsh11send87575cost150pday6days16tsandcsapplyreplyhl4info,urgent1weekfreemembership100000prizejackpottxtwordclaim81010tcwwwdbuknetlccltdpobox4403ldnw1a7rw18,winnervaluednetworkcustomerselectedreceivea900prizerewardclaimcall09061701461claimcodekl341valid12hour,xxxmobilemovieclubusecreditclickwaplinknexttxtmessageclickhttpwapxxxmobilemovieclubcomnqjkgighjjgcbl,üpayfirstlardastockcomin
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
7,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
12,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
13,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
19,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### TF-IDF

Creates a document-term matrix where the columns represent single unique terms (unigrams) but the cell represents a weighting meant to represent how important a word is to a document.

In [72]:
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [PS.stem(word) for word in tokens if word not in stopwords]
    return text

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(analyzer=clean_text)
X_tfidf = tfidf_vect.fit_transform(data['body_text'])
# print(X_tfidf.shape)
# print(tfidf_vect.get_feature_names

X_tfidf_df = pd.DataFrame(X_tfidf.toarray())
X_tfidf_df.columns = tfidf_vect.get_feature_names_out()
X_tfidf_df

<>:3: SyntaxWarning: invalid escape sequence '\W'
<>:3: SyntaxWarning: invalid escape sequence '\W'
C:\Users\ayray\AppData\Local\Temp\ipykernel_22108\3516843870.py:3: SyntaxWarning: invalid escape sequence '\W'
  tokens = re.split('\W+', text)

,,0,008704050406,0089mi,0121,01223585236,01223585334,0125698789,02,020603,...,zindgi,zoe,zogtoriu,zoom,zouk,zyada,é,ü,üll,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
5564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.335215,0.0,0.0
5565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
5566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [74]:
data_sample = data[0:20]

tfidf_vect_sample = TfidfVectorizer(analyzer=clean_text)
X_tfidf_sample = tfidf_vect_sample.fit_transform(data_sample['body_text'])
print(X_tfidf_sample.shape)
print(tfidf_vect_sample.get_feature_names_out())

X_tfidf_df = pd.DataFrame(X_tfidf_sample.toarray())
X_tfidf_df.columns = tfidf_vect_sample.get_feature_names_out()
X_tfidf_df

(20, 201)
['08002986030' '08452810075over18' '09061701461' '1' '100' '100000' '11'
 '12' '150pday' '16' '2' '20000' '2005' '21st' '3' '4' '4403ldnw1a7rw18'
 '4txtú120' '6day' '81010' '87077' '87121' '87575' '9' '900' 'aft' 'aid'
 'alreadi' 'anymor' 'appli' 'ard' 'around' 'b' 'bless' 'breather'
 'brother' 'call' 'caller' 'callertun' 'camera' 'cash' 'chanc' 'claim'
 'click' 'co' 'code' 'colour' 'comin' 'comp' 'copi' 'cost' 'credit' 'cri'
 'csh11' 'cup' 'custom' 'da' 'date' 'dont' 'eg' 'eh' 'england' 'enough'
 'entitl' 'entri' 'even' 'fa' 'feel' 'final' 'fine' 'finish' 'first'
 'free' 'friend' 'fulfil' 'go' 'goalsteam' 'goe' 'gonna' 'gota' 'grant'
 'ha' 'help' 'hl' 'home' 'hour' 'httpwap' 'im' 'info' 'ive' 'jackpot'
 'joke' 'k' 'kim' 'kl341' 'lar' 'latest' 'lccltd' 'like' 'link' 'live'
 'lor' 'lunch' 'macedonia' 'make' 'may' 'mell' 'membership' 'messag'
 'minnaminungint' 'miss' 'mobil' 'month' 'nah' 'name' 'nation' 'naughti'
 'network' 'news' 'next' 'nurungu' 'oh' 'oru' 'patent' 'pay' 'per' 'pobox'
 'poboxox36504w45wq' 'pound' 'press' 'prize' 'promis' 'questionstd' 'r'
 'ratetc' 'receiv' 'receivea' 'rememb' 'repli' 'request' 'reward' 'right'
 'scotland' 'search' 'select' 'send' 'serious' 'set' 'six' 'smth' 'soon'
 'speak' 'spell' 'stock' 'str' 'stuff' 'sunday' 'take' 'talk' 'tc' 'team'
 'text' 'thank' 'think' 'though' 'time' 'tkt' 'today' 'tonight' 'treat'
 'tri' 'trywal' 'tsandc' 'txt' 'u' 'updat' 'ur' 'urgent' 'use' 'usf' 'v'
 'valid' 'valu' 'vettam' 'want' 'wap' 'watch' 'way' 'week' 'wet' 'win'
 'winner' 'wkli' 'wonder' 'wont' 'word' 'wwwdbuknet' 'xxxmobilemovieclub'
 'xxxmobilemovieclubcomnqjkgighjjgcbl' 'ye' 'ü']

,08002986030,08452810075over18,09061701461,1,100,100000,11,12,150pday,16,...,winner,wkli,wonder,wont,word,wwwdbuknet,xxxmobilemovieclub,xxxmobilemovieclubcomnqjkgighjjgcbl,ye,ü
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.238737,0.238737,0.209853,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.198986,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.198986,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.231645,0.000000,0.000000,0.000000,0.000000,0.231645,0.000000,0.000000,...,0.231645,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.197682,0.000000,0.000000,0.000000,0.000000,0.000000,0.197682,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.224905,0.000000,0.000000,0.000000,0.224905,0.197695,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.254832,0.000000,0.254832,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.224001,0.254832,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.272652,0.272652,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.291197,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.185730,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377964
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## Lets build a classifier model on the vectorized texts

In [75]:
import nltk
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import string

stopwords = nltk.corpus.stopwords.words('english')
ps = nltk.PorterStemmer()

data = pd.read_csv("SMSSpamCollection.tsv", sep='\t')
data.columns = ['label', 'body_text']

def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return round(count/(len(text) - text.count(" ")), 3)*100

data['body_len'] = data['body_text'].apply(lambda x: len(x) - x.count(" ")) ## counts distinct words
# data['punct%'] = data['body_text'].apply(lambda x: count_punct(x))

def clean_text(text): 
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

<>:22: SyntaxWarning: invalid escape sequence '\W'
<>:22: SyntaxWarning: invalid escape sequence '\W'
C:\Users\ayray\AppData\Local\Temp\ipykernel_22108\838022420.py:22: SyntaxWarning: invalid escape sequence '\W'
  tokens = re.split('\W+', text)

In [76]:
data.head()

  label                                          body_text  body_len
0  spam  Free entry in 2 a wkly comp to win FA Cup fina...       128
1   ham  Nah I don't think he goes to usf, he lives aro...        49
2   ham  Even my brother is not like to speak with me. ...        62
3   ham                I HAVE A DATE ON SUNDAY WITH WILL!!        28
4   ham  As per your request 'Melle Melle (Oru Minnamin...       135

In [77]:
from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(data[['body_text', 'body_len', 'punct%']], data['label'], test_size=0.2)
X_train, X_test, y_train, y_test = train_test_split(data[['body_text', 'body_len']], data['label'], test_size=0.2)

### Vectorize text using TFIDF vectorizer

In [78]:
tfidf_vect = TfidfVectorizer(analyzer=clean_text)
tfidf_vect_fit = tfidf_vect.fit(X_train['body_text'])

train_imp = pd.concat([train_imp, pd.DataFrame(train_reviews.toarray()).add_prefix('review')], axis=1)
test_imp = pd.concat([test_imp, pd.DataFrame(test_reviews.toarray()).add_prefix('review')], axis=1)

tfidf_train = tfidf_vect_fit.transform(X_train['body_text'])
tfidf_test = tfidf_vect_fit.transform(X_test['body_text'])

X_train_vect = pd.concat([X_train[['body_len']].reset_index(drop=True), 
           pd.DataFrame(tfidf_train.toarray())], axis=1)

X_test_vect = pd.concat([X_test[['body_len']].reset_index(drop=True), 
           pd.DataFrame(tfidf_test.toarray())], axis=1)

X_train_vect.head()

,body_len,0,1,2,3,4,5,6,7,8,...,7170,7171,7172,7173,7174,7175,7176,7177,7178,7179
0,134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,103,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,112,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
X_train_vect.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4453 entries, 0 to 4452
Columns: 7181 entries, body_len to 7179
dtypes: float64(7180), int64(1)
memory usage: 244.0 MB

In [82]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import precision_recall_fscore_support as score
import time

rf = RandomForestClassifier(n_estimators=150, max_depth=None)

X_train_vect.columns = X_train_vect.columns.astype(str)
start = time.time()
rf_model = rf.fit(X_train_vect, y_train)
end = time.time()
fit_time = (end - start)

X_test_vect.columns = X_test_vect.columns.astype(str)
start = time.time()
y_pred = rf_model.predict(X_test_vect)
end = time.time()
pred_time = (end - start)

precision, recall, fscore, train_support = score(y_test, y_pred, pos_label='spam', average='binary')
print('Fit time: {} / Predict time: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
    round(fit_time, 3), round(pred_time, 3), round(precision, 3), round(recall, 3), round((y_pred==y_test).sum()/len(y_pred), 3)))

Fit time: 21.859 / Predict time: 0.325 ---- Precision: 1.0 / Recall: 0.812 / Accuracy: 0.977